### PR TITLE
fix: use client for button

### PR DESCRIPTION
**Pull request by glitch-txs**

### CODE REVIEW

**Comment by mubshrx** [comment]
Have you tried and does it work?

**Comment by glitch-txs** [comment]
Yes, connect kit button shows on screen.

**Comment by mubshrx** [comment]
Did you try connecting to a wallet?

**Comment by glitch-txs** [comment]
my bad! I thought the issue was with the initial render, I got the error however this uses wagmi v0 which is outdated, do you happen to have an example without connectKit (only wagmi)? updating it to its latest version get me other errors...

**Pull request closed without merging**
